### ISSUE TITLE
Thank you for updating the KAP140

### ISSUE THREAD

**Issue by BPieke** [FS2020-USER-TESTER/KAP140-MOD-PACKAGE#3]
I just flew it with the Milviz C310 and it works brilliantly!

Really pleased that all AP modes turn off when the autopilot is turned off.

Thanks again!

BP

**Comment by FS2020-USER-TESTER** [comment]
Glad you find it useful.  I find I am fascinated by the aircraft coding in MSFS.  Really complex. This project was an attempt to understand better the javascript.

**Comment by BPieke** [comment]
I like what you have done, but just one question... is the "GPS" readout a personal touch?  The real world KAP 140 Pilots guide only has NAV.. at least my copy..
